### PR TITLE
Added responsive styles and screenshots

### PR DESCRIPTION
**Pull request by raquelmangual**
This pull request included updated responsive styles that fixes issues with an image, and screenshots for preview before approving.

### CODE REVIEW

**Comment by scorcism** [comment]
Hey you did a great job, but can you fix header part ?
It looks little dazzy

**Comment by raquelocasio** [comment]
> 

Sure I can fix, but can you specify what you'd like?

**Comment by raquelmangual** [comment]
I've updated the responsive styles for the header navigation. Also included an updated screenshot for the view on smaller screens (responsive2.png)

> Hey you did a great job, but can you fix header part ? It looks little dazzy

**Comment by scorcism** [comment]
well done buddy.

**Pull request merged**
